<?php

//ARRAY CRIADO AUTOMATICAMENTE, CONTENDO AS VARIAVEIS ENVIADAS POR MÉTODO GET
print_r($_GET);


//ARRAY CRIADO AUTOMATICAMENTE, CONTENDO AS VARIAVEIS ENVIADAS POR MÉTODO POST
print_r($_POST);


//FAÇA COM QUE A PÁGINA EXIBA OS VALORES INFORMADOS NO FORMULÁRIO

//NÃO ESQUEÇA DE ACRESCENTAR CABECALHO E RODAPE EM SUA PÁGINA

